import { Plant, Listing, Conversation, UserProfile } from "./types";

export const FALLBACK_USER: UserProfile = {
  id: "user_emma",
  email: "demo@floracare.local",
  name: "Emma Hartwell",
  avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop&auto=format",
  bio: "Passionate urban jungle collector & rare aroid lover",
  location: "Brooklyn, NY",
};

export const FALLBACK_PLANTS: Plant[] = [
  {
    id: "1",
    userId: "user_emma",
    nickname: "Big Mo",
    species: "Monstera Deliciosa",
    scientificName: "Monstera deliciosa",
    status: "healthy",
    image: "https://images.unsplash.com/photo-1545241047-6083a3684587?w=800&h=800&fit=crop&auto=format",
    wateringFrequency: 7,
    lastWatered: new Date(Date.now() - 2 * 86400000).toISOString(),
    notes: "New leaf unfurling! Keep away from direct afternoon sun.",
    sunlight: "Bright indirect light",
    soil: "Chunky aroid mix with bark & perlite",
    temperature: "65–85°F (18–29°C)",
    humidity: "60%+",
    fertilizer: "Monthly in spring & summer",
    createdAt: new Date().toISOString(),
  },
  {
    id: "2",
    userId: "user_emma",
    nickname: "Trailing Grace",
    species: "Golden Pothos",
    scientificName: "Epipremnum aureum",
    status: "due-soon",
    image: "https://images.unsplash.com/photo-1509423350716-97f9360b4e09?w=800&h=800&fit=crop&auto=format",
    wateringFrequency: 5,
    lastWatered: new Date(Date.now() - 4 * 86400000).toISOString(),
    notes: "Propagated three cuttings last month. Growing fast.",
    sunlight: "Medium to low indirect light",
    soil: "Standard potting mix",
    temperature: "60–80°F (15–26°C)",
    humidity: "Average 40–50%",
    fertilizer: "Bi-monthly dilute",
    createdAt: new Date().toISOString(),
  },
  {
    id: "3",
    userId: "user_emma",
    nickname: "Rocky",
    species: "Snake Plant",
    scientificName: "Sansevieria trifasciata",
    status: "healthy",
    image: "https://images.unsplash.com/photo-1593691509543-c55fb32e3de5?w=800&h=800&fit=crop&auto=format",
    wateringFrequency: 14,
    lastWatered: new Date(Date.now() - 5 * 86400000).toISOString(),
    notes: "Nearly indestructible. Repotted to a 6-inch terracotta.",
    sunlight: "Any light level",
    soil: "Cactus & gritty mix",
    temperature: "55–85°F (13–29°C)",
    humidity: "Low humidity tolerant",
    fertilizer: "Rarely, once a quarter",
    createdAt: new Date().toISOString(),
  },
  {
    id: "4",
    userId: "user_emma",
    nickname: "Lily",
    species: "Peace Lily",
    scientificName: "Spathiphyllum wallisii",
    status: "overdue",
    image: "https://images.unsplash.com/photo-1560717789-0ac7c58ac90a?w=800&h=800&fit=crop&auto=format",
    wateringFrequency: 7,
    lastWatered: new Date(Date.now() - 10 * 86400000).toISOString(),
    notes: "Tends to droop dramatically when thirsty. Very dramatic.",
    sunlight: "Low to bright indirect",
    soil: "Peat-based mix",
    temperature: "65–80°F (18–27°C)",
    humidity: "High 60%+",
    fertilizer: "Every 6 weeks",
    createdAt: new Date().toISOString(),
  },
];

export const FALLBACK_LISTINGS: Listing[] = [
  {
    id: "1",
    sellerId: "user_sarah",
    plantName: "Monstera Cutting",
    species: "Monstera deliciosa",
    price: 35,
    area: "Brooklyn, NY",
    date: "Jul 28",
    image: "https://images.unsplash.com/photo-1545241047-6083a3684587?w=600&h=600&fit=crop&auto=format",
    description: "Healthy cutting with 2 nodes and one aerial root. Well-established, ready to pot. From a smoke-free home.",
    available: true,
    createdAt: new Date().toISOString(),
    seller: {
      id: "user_sarah",
      name: "Sarah Jenkins",
      avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop&auto=format",
      rating: 4.9,
    },
  },
  {
    id: "2",
    sellerId: "user_marco",
    plantName: "Rare Alocasia Zebrina",
    species: "Alocasia zebrina",
    price: 80,
    area: "Manhattan, NY",
    date: "Jul 25",
    image: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=600&h=600&fit=crop&auto=format",
    description: "Stunning Alocasia Zebrina, about 14 inches tall. Comes in a 4-inch nursery pot. Has been thriving indoors.",
    available: true,
    createdAt: new Date().toISOString(),
    seller: {
      id: "user_marco",
      name: "Marco Rossi",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&auto=format",
      rating: 5.0,
    },
  },
];

export const FALLBACK_CONVERSATIONS: Conversation[] = [
  {
    id: "conv_1",
    listingId: "1",
    listing: "Monstera Cutting",
    listingImage: "https://images.unsplash.com/photo-1545241047-6083a3684587?w=100&h=100&fit=crop&auto=format",
    listingPrice: 35,
    sellerId: "user_sarah",
    buyerId: "user_emma",
    otherParty: {
      id: "user_sarah",
      name: "Sarah Jenkins",
      avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop&auto=format",
    },
    lastMessage: "Sure! I can meet at the farmer's market on Saturday morning.",
    time: "2h ago",
    unread: 1,
    messages: [
      { id: "m1", role: "user", senderId: "user_emma", text: "Hi Sarah! Is the Monstera cutting still available?", time: "Yesterday", createdAt: new Date().toISOString() },
      { id: "m2", role: "other", senderId: "user_sarah", text: "Yes, still available! It has great healthy roots.", time: "Yesterday", createdAt: new Date().toISOString() },
      { id: "m3", role: "other", senderId: "user_sarah", text: "Sure! I can meet at the farmer's market on Saturday morning.", time: "2h ago", createdAt: new Date().toISOString() },
    ],
  },
];
